name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  key-vault-name:
    required: true
    description: 'name of the azure key vault'
  config:
    required: true
    description: 'github secret name to key vault secret name mapping'
runs:
  using: 'node16'
  main: 'dist/index.js'
