name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  id-token: write
  contents: read

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: e0300a0f-e375-479f-958c-4634e90db7e7
          tenant-id: 4a3b9c18-eabb-4dc0-b5e9-6a82f2eb9f6a
          subscription-id: 2cdafa7b-c9b6-43b0-92b3-7561c34a5e17

      - name: 'Run Azure CLI commands'
        run: |
          az account show
      - uses: ./
        with:
          key-vault-name: keyvault-test34
          config: |
            {"TEST": "test"}
      - run: echo "${{ env.TEST }}"
